### ISSUE TITLE
Tables Key List - Enabled property

### ISSUE THREAD

**Issue by sergioramos83** [dynasist/ALStudio#10]
Hi team,

Don't know if this is a issue but makes me confusion when looking the keys of a table, see example below:

Table 37 - Key 2 when we look it appears that is enabled.
![image](https://user-images.githubusercontent.com/13440034/96853415-9e470a00-145a-11eb-9aa2-29f8653c275b.png)

But if we look the source code, the enabled = false.
![image](https://user-images.githubusercontent.com/13440034/96853674-ee25d100-145a-11eb-943d-98c3604b50f9.png)

I look into the other keys and it looks like that on key list this property is showing the opposite value. If enabled = true shows false, if enabled = false shows true.

This is just a remark but i think that makes some confusion when we search for keys using the key list.

Thanks

**Comment by martonsagi** [comment]
Hello,

Thank you for the feedback, we are fixing this shortly. In general, we we'll be focusing on fixing designer issues next week.

**Comment by sergioramos83** [comment]
Great!

Thanks

**Comment by martonsagi** [comment]
Enabled switch has been fixed, the update is now being published on Marketplace. It will be available within the hour.
A more thorough review is also underway to properly show the default value of properties (e.g. Enabled or Editable is true by default even without defining it explicitly).
