### ISSUE TITLE
NullReference Exception On CreateTable Extension

### ISSUE THREAD

**Issue by FBakkensen** [dynasist/ALStudio#11]
I am making an extension for a BC 15.3, and when I from the table list click the 3 dots and select extend, i get the Error shown.

`An unexpected error occurred invoking 'ExtendObject' on the server. NullReferenceException: Object reference not set to an instance of an object.`

This is from the Output:
```
[AL Studio][2020-11-02T09:25:17.490Z][Debug]: dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "22", Target: "ExtendObject", Arguments: [ ALObjectDesigner.Library.SymbolData ], StreamIds: [  ] }.

[AL Studio][2020-11-02T09:25:17.509Z][Debug]: fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'ExtendObject'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at ALStudio.Server.Services.ALObjectService.ExtendObject(SymbolData info)
         at ALStudio.Server.ALStudioHub.ExtendObject(SymbolData info)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass16_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()

```

**Comment by martonsagi** [comment]
Hello Flemming,

Thank your for reporting this issue, we'll look into it shortly.

**Comment by martonsagi** [comment]
The issue has been fixed, it will be rolled out tomorrow, after internal testing.

Note: make sure to check the selected application in the app dropdown before extending an object. 
* That will be the target app and it must be different from the base object's application.
* Extended objects will be placed in the selected app's folder.

It's no problem when extending an object from BaseApp or System App. Although it might need attention if you have more apps in a workspace depending on each other.
E.g. When extending "Ticket App"."Ticket" table, the selected application cannot be "Ticket App".

![image](https://user-images.githubusercontent.com/18100709/97883996-d3d6d780-1d25-11eb-8abf-b3a8c7585ba1.png)
