### ISSUE TITLE
Navigate to WORD/RDCL layout that belongs to a report object that resides in a symbol file

### ISSUE THREAD

**Issue by lvanvugt** [dynasist/ALStudio#12]
At this moment it's not possible to navigate from VSCode to the WORD/RDCL layout that belongs to a report object that resides in a symbol file. Would be great if this would be made possible.

**Comment by martonsagi** [comment]
I have added new menus to the context menu on AL Home screen.

* Layout Source: visible for RDLC reports, opens the .rdl file as a new xml document. This way you can save it as a new file, hence duplicating the original
* Open Layout: visible for RDLC/Word reports. Opens up the report layout in the proper editor (Microsoft Word or Report Builder)

There is some unit test fixing that needs to be before releasing it to the Marketplace, but you can expect it for today.

![ALStudio_ReportLayoutOpen](https://user-images.githubusercontent.com/18100709/98509525-a62bea00-2261-11eb-9a0a-27d98e37870b.gif)

**Comment by martonsagi** [comment]
Btw, it works for local workspace files as well. In that case, of course, you can edit the files right away.

**Comment by martonsagi** [comment]
This feature has been published to the Marketplace, you can test it.

**Comment by lvanvugt** [comment]
Thanx and great. Only challenge is that my VSCode installation does not open Report Builder automatically. Need to find out what's wrong. WORD works fine.
Testes indeed the download and that's fine.

**Comment by lvanvugt** [comment]
@martonsagi still one thing: how to get WORD and RDLC layout opened it they exist for a report?

REP1305 has both WORD and RDLC layout, but as WORD is default layout it will now only open WORD layout. It seems I have no way of opening RDLC layout in VSCode (both as source in VSCode and layout in Report Builder).

**Comment by martonsagi** [comment]
Oh, yes. Currently default layout is shown. I'll make an adjustment to always check both rdlclayout and wordlayout properties regardless of defaultlayout.

**Comment by martonsagi** [comment]
I made the change in behaviour. You will see the RDLC/Word buttons based on RDLCLayout/WordLayout properties.
Testing and publishing need some time, but I'm planning to publish it today.

![image](https://user-images.githubusercontent.com/18100709/98588391-eb850180-22cb-11eb-8e44-cee8d2cd758a.png)

**Comment by martonsagi** [comment]
It has already been published, no issues reported, so I'm closing this one. :)

**Comment by lvanvugt** [comment]
Indeed no issues. Looks good! Thanx for adding.
