### ISSUE TITLE
Need to unblock for firewall on every update

### ISSUE THREAD

**Issue by NKarolak** [dynasist/ALStudio#13]
On every single update of the extension, I need to unblock it  again from the Windows Defender Firewall:
![image](https://user-images.githubusercontent.com/34504100/100579425-89c12180-32e4-11eb-9261-330ce4de02e0.png)

Is there a chance to save the setting?

**Comment by martonsagi** [comment]
Strange, I only needed to do it once. I'll check whether we can get rid of the firewall warning altogether or not.

**Comment by martonsagi** [comment]
I have a possible solution, I will send you a custom build to test it.

**Comment by NKarolak** [comment]
Works, no request from Defender anymore :-)
