### ISSUE TITLE
alstudio.scopes.json when no scopes?

### ISSUE THREAD

**Issue by waldo1001** [dynasist/ALStudio#17]
Is it really necessary to create the scopes-json when not using scopes?

it creates "changes" in git ...
![image](https://user-images.githubusercontent.com/12088142/101164249-2103dd00-3635-11eb-978a-7590073812c0.png)

**Comment by martonsagi** [comment]
Uhm, no. I've changed this behaviour. File will be created when first scope is added.

**Comment by martonsagi** [comment]
The related update will be published tomorrow on the Marketplace.
