### ISSUE TITLE
Cannot open Layout (RDLC) of my own *.rdlc files

### ISSUE THREAD

**Issue by NKarolak** [dynasist/ALStudio#18]
I am developing an extension depending on the Base Application.

AL Home Screen: 

1. When I navigate to a standard RDLC report, e.g. 205 Order Confirmation, and then choose "Layout (RDLC)", the Report Builder will open and display the layout as expected.

2. When I copy this standard report + rdlc file to my workspace, AL Studio can open its layout as well.

3. But when I create a new report + rdlc layout, then I cannot open it: `Failed to open file 'name.rdlc'.`
This is the same error I would get when trying to open ANY rdlc file externally with Report Builder, also the working standard ones.
(I would need to rename the file into *.rdl. This is what the docs instruct anyway: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-howto-rdl-report-layout#create-an-rdl-layout-report )

However, I am wondering why then AL Studio _is_ able to open the RDLC files, except my own? I tried to find any relevant differences between both workspace reports, but so far without any success.

**Comment by martonsagi** [comment]
Hi Natalie,

RDLC files from symbol packages are copied to a temp file and being saved with .RDL extension. After that it just calls the VSCode openExternal command that tries to open any file with its associated editor.

**Comment by NKarolak** [comment]
I see, so AL Studio should better not touch the local file to rename it.
Result: Stick to the docs --> use RDL files only.

Thanks, Márton!
