### ISSUE TITLE
Cannot open Page Actions Source

### ISSUE THREAD

**Issue by NKarolak** [dynasist/ALStudio#19]
Using the Actions overview of a page (e.g. of page Posted Sales Invoices), and placing the cursor of an arbirary action below, it is not possible to run action "Source":

`Application_1.Application.objectList.find is not a function`

![image](https://user-images.githubusercontent.com/34504100/103785313-58eaaf80-503b-11eb-9764-6b1a16cb78e6.png)

**Comment by martonsagi** [comment]
Is this loaded from a BaseApp with actual source or from a Symbol in an extension project?

**Comment by NKarolak** [comment]
From a symbol in an extension project

**Comment by martonsagi** [comment]
I can't seem to be able to reproduce it with a BC17.2 project. Am I doing it right?

![ALStudio_PageMenuDebug](https://user-images.githubusercontent.com/18100709/103791291-930b7f80-5042-11eb-954e-542db369aea8.gif)

**Comment by NKarolak** [comment]
My computer is already shut down, but you can see from my screenshot that I've chosen the Actions tab, not the Layout tab. Can you try that?

**Comment by martonsagi** [comment]
Result is the same, source is still loaded.

**Comment by NKarolak** [comment]
Today I cannot reproduce it either. No idea.
Sorry for having bothered you :-)

**Comment by martonsagi** [comment]
There was an unrelated hotfix published yesterday evening. Well, I'm glad it works now. :)
