### ISSUE TITLE
Extension causes high cpu load: Debugger affected

### ISSUE THREAD

**Issue by NKarolak** [dynasist/ALStudio#24]
Hi Márton,

VS Code told me to notify you about
![image](https://user-images.githubusercontent.com/34504100/110590880-a89f4180-8178-11eb-88c8-161925c974e2.png)
after I reloaded VS Code. During that, VS Code was generally hardly responding, and I am questioning that ALStudio was the cause, but also only suffering from it.

- Issue Type: `Performance`
- Extension Name: `al-studio`
- Extension Version: `0.9.880`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.1`

My CPU profile:
[dynasist.al-studio-unresponsive.cpuprofile - Copy.txt](https://github.com/dynasist/ALStudio/files/6113951/dynasist.al-studio-unresponsive.cpuprofile.-.Copy.txt)

I could not reproduce it since.
But I thought to post it anyway, just in case the CPU profile might contain something useful for you.

**Comment by NKarolak** [comment]
Oh, it happened again after I debugged
![image](https://user-images.githubusercontent.com/34504100/110592253-58c17a00-817a-11eb-94c3-e9c1f1d5a702.png)

**Comment by NKarolak** [comment]
Okay, this is an AL Studio issue, unfortunately:
Only when AL Studio is enabled, certain code stops the debugger from proceeding, as initially reported in the AL repo:
https://github.com/microsoft/AL/issues/6520

The affected code is
![image](https://user-images.githubusercontent.com/34504100/110594342-f4ec8080-817c-11eb-8074-1f1dc84b7636.png)

Please let me know how to proceed.

**Comment by martonsagi** [comment]
Hi Natalie,

Thanks for the help in the debugging, I was able to pinpoint the issue and the hotfix is on its way to the Marketplace.
