### ISSUE TITLE
Unexpected Go To Definition when using the Ctrl key

### ISSUE THREAD

**Issue by NKarolak** [dynasist/ALStudio#9]
This one is quite critical :-D

v0.9.568 introduced a feature to link objects from code for a quick Go To Definition (F12).
But it overrules all shortcuts starting with Ctrl.

Feature?
Press and hold Ctrl, and then hover (!) on a codeunit variable name --> the codeunit will be opened in a new tab.

Side effect = bug
Try e.g. to delete a line using Ctrl+Shift+K, while your cursor is on the variable name.
The moment you press Ctrl, the objects is opened, hence you cannot use the shortcut.

**Comment by martonsagi** [comment]
I have removed the custom Definition provider for now. AL Language on itself seems to be capable now of what I also implemented earlier (perhaps implicit updates with Wave2).
This way, the operation goes back to normal.  (Although my provider was faster but I can't replace it, only duplicate the functionality).

Marketplace will be updated soon.

**Comment by NKarolak** [comment]
v0.9.570 now works like expected:
- Pressing and holding the Ctrl button + hover over variable/object names now creates links. Only when clicking on the link, the object is opened.
- Ctrl+Shift+K works again.

Thanks a lot for your quick help! 😊
